#!/bin/bash

# Interactive shell for running codeql queries
#
# Usage:
#   qlsh <database>
#
# Run `qlsh` on its own for more help
#
# Requires codeql, bash, jq and (optionally) rlwrap, curl and lynx to be installed
#
# Copyright (C) 2024, GitHub

set -euo pipefail

function codeql_shell_set_ram {
    # set the initial amount of RAM to use for CodeQL queries
    # default is all of the RAM on the system, minus 1GB
    if command -v free &> /dev/null; then
        # get total RAM in bytes
        total_ram=$(free -b | awk '/^Mem:/{print $2}')
        # set _codeql_ram to 1GB less than total RAM
        total_ram_mb=$(( ( total_ram / ( 1024  * 1024 ) ) - 1024))
        _codeql_ram="${total_ram_mb}"
    elif command -v sysctl &> /dev/null; then
        # get total RAM in bytes on macOS
        total_ram=$(sysctl -n hw.memsize)
        # set _codeql_ram to 1GB less than total RAM
        total_ram_mb=$(( ( total_ram / ( 1024  * 1024 ) ) - 1024))
        _codeql_ram="${total_ram_mb}"
    else
        echo "[-] free or sysctl command not found, using default RAM setting" >&2
        _codeql_ram=7168  # fallback to 7GB if neither command is available
    fi
}

function codeql_shell_write_qlpack {
    cat <<EOF > "${_query_file_directory}"/qlpack.yml
name: advanced-security/${_language}-repl-query
version: 0.0.0
extractor: ${_language}
groups:
- ${_language}
dependencies:
    codeql/${_language}-all: "*"
EOF
}

function codeql_shell_resolve_languages {
    # check if the language is supported, try to download pack if not
    (
        cd "${_query_file_directory}" || ( echo "Failed to change directory to temporary query directory, exiting" >&2 && exit 1 )

        codeql pack install --quiet "${_query_file_directory}" > /dev/null 2>&1 || ( echo "[-] Error installing codeql pack(s)" >&2 && exit 1 )

        if ! codeql resolve languages --format=json | jq -e ".${_language}" > /dev/null 2>&1; then
            echo "[.] Language not supported, attempting to install codeql pack(s)" >&2
            if ! codeql pack install --force "${_query_file_directory}" > /dev/null 2>&1; then
                echo "[-] Error installing codeql pack(s)" >&2
                exit 1
            fi
        fi
    )
}

function codeql_shell_cleanup {
    rm -f "${_bqrs_path}"
    rm -f "${_query_file}"
}

function codeql_shell_quit {
    codeql_shell_cleanup
    exit 0
}

function codeql_shell_help {
    echo "CodeQL Shell, qlsh" >&2
    echo "" >&2
    echo "Usage: qlsh <database>" >&2
    echo "" >&2
    echo "Interactive shell for running codeql queries." >&2
    echo "" >&2
    echo "Every query is built line-by-line and run when a 'select' statement is detected (a line starting with 'select ')." >&2
    echo "" >&2
    echo "Bundled (zipped) databases are automatically extracted to a temporary folder." >&2
    echo "" >&2
    echo "The language of the database is autodetected, and put into the query." >&2
    echo "" >&2
    echo "If the language of the database is not supported, the script will attempt to download the required pack." >&2
    echo "" >&2
    echo "Commands:" >&2
    echo "  quit: exit the shell (or use Ctrl-D)" >&2
    echo "  help: display this help message" >&2
    echo "  help <search term>: search CodeQL online library for provided terms" >&2
    echo "  show: print the current query buffer" >&2
    echo "  lang: print the language of the database" >&2
    echo "  dir: print the directory of the query file" >&2
    echo "  reset: clear the current query buffer (or use Ctrl-C)" >&2
    echo "  unlock: remove the .lock file from the current database's default/cache directory" >&2
    echo "  set ram <amount>: set the amount of RAM in MB to use for CodeQL queries (default is all available RAM minus 1GB)" >&2
    echo "  set cores <number>: set the number of CPU cores to use for CodeQL queries (default is all available cores minus one)" >&2
    echo "  set paged <on|off>: set paging of output on or off" >&2
    echo "  set: print the current RAM, cores and paging settings" >&2
    echo "" >&2
}

function codeql_shell_help_lookup {
    # lookup help in CodeQL docs for a specific command
    # search details taken from https://codeql.github.com/codeql-standard-libraries/search.html

    if [[ -z "$1" ]]; then
        echo "[-] Please provide a search term, e.g. 'help <search term>'" >&2
        return
    fi

    # escape the search term for use in a URL
    search="$(echo "$1" | jq --slurp --raw-input --raw-output @uri)"

    codeql_search_cdn_url="https://s11.searchcdn.com/93b4d287e2fc079a4089412b669785d5/${search}/0/1380/?s=1748954834507&categories=2x${_language}"

    if command -v curl &> /dev/null; then
        result_url=$(curl -s "${codeql_search_cdn_url}" | \
        # remove 'addsearch.searchResults(' prefix and ');' suffix
        sed 's/^addsearch.searchResults(//;s/);$//' | \
        # extract the first result
        jq '.es.hits.hits[0].fields.url' | \
        # remove quotes around URL
        sed 's/"//g')

        if [[ -z "${result_url}" ]]; then
            echo "[-] No online help found for ${1}" >&2
            return
        fi

        # open with text browser if available
        if command -v lynx &> /dev/null; then
            if [[ "on" == "${_codeql_shell_paged}" ]]; then
                lynx -dump "${result_url}"  | less
            else
                lynx -dump "${result_url}"
            fi

        else
            echo "Online help: ${result_url}"
        fi

    else
        echo "[-] curl not found, cannot give online help" >&2
    fi
}

function codeql_shell_prompt {
    echo -n "${_codeql_shell_prompt}"
}

function codeql_shell_write_language {
    echo "import ${_language}" >> "${_query_file}"
}

function codeql_shell_trunc {
    truncate -s 0 "${_query_file}"
}

function codeql_shell_restart {
    codeql_shell_trunc
    codeql_shell_write_language
    _codeql_shell_prompt="codeql> "
    codeql_shell_prompt
}

function codeql_shell_cont {
    _codeql_shell_prompt="... "
    codeql_shell_prompt
}

function codeql_shell_restart_sigint {
    # catch SIGINT
    tput setaf 1
    tput sgr0

    echo
    codeql_shell_restart
}

function codeql_shell_repl {
    trap codeql_shell_cleanup EXIT
    trap codeql_shell_restart_sigint INT

    codeql_shell_restart

    while read -r line; do
        # handle REPL commands
        if [[ "${line}" == "quit" ]]; then
            break
        fi

        if [[ "${line}" == "help" ]]; then
            codeql_shell_help
            codeql_shell_prompt
            continue
        fi

        codeql_shell_regex_help="^help "

        if [[ "${line}" =~ $codeql_shell_regex_help ]]; then
            codeql_shell_help_lookup "$(echo "${line}" | cut -d " " -f2-)"
            codeql_shell_prompt
            continue
        fi

        if [[ "${line}" == "show" ]]; then
            cat "${_query_file}"
            codeql_shell_prompt
            continue
        fi

        if [[ "${line}" == "reset" ]]; then
            codeql_shell_restart
            continue
        fi

        if [[ "${line}" == "lang" ]]; then
            echo "${_language}"
            codeql_shell_prompt
            continue
        fi

        if [[ "${line}" == "set" ]]; then
            echo "RAM: ${_codeql_ram} MB / $(( _codeql_ram / 1024 )) GB"
            echo "Cores: ${_codeql_cores}"
            echo "Output paging with 'less': ${_codeql_shell_paged}"
            codeql_shell_prompt
            continue
        fi

        if [[ "${line}" == "dir" ]]; then
            echo "${_query_file_directory}"
            codeql_shell_prompt
            continue
        fi

        if [[ "${line}" == "unlock" ]]; then
            lock_file="${_db_path}/db-${_language}/default/cache/.lock"
            if [[ -f "$lock_file" ]]; then
                rm -f "$lock_file"
                echo "[+] Lock file removed: $lock_file"
            else
                echo "[.] No lock file found at $lock_file"
            fi
            codeql_shell_prompt
            continue
        fi

        if [[ "${line}" =~ ^set\ ram\  ]]; then
            value="${line#set ram }"
            if [[ -n "$value" ]]; then
                _codeql_ram="$value"
                echo "[+] RAM set to $_codeql_ram"
            else
                echo "[-] Please provide a value, e.g. 'set ram 8000M'"
            fi
            codeql_shell_prompt
            continue
        fi

        if [[ "${line}" =~ ^set\ cores\  ]]; then
            value="${line#set cores }"
            if [[ -n "$value" ]]; then
                _codeql_cores="$value"
                echo "[+] Cores set to $_codeql_cores"
            else
                echo "[-] Please provide a value, e.g. 'set cores 4'"
            fi
            codeql_shell_prompt
            continue
        fi

        if [[ "${line}" =~ ^set\ paged\  ]]; then
            value="${line#set paged }"
            if [[ "$value" == "on" ]]; then
                _codeql_shell_paged='on'
                echo "[+] Output paging enabled"
            elif [[ "$value" == "off" ]]; then
                _codeql_shell_paged='off'
                echo "[+] Output paging disabled"
            else
                echo "[-] Please provide a value, either 'on' or 'off'"
            fi
            codeql_shell_prompt
            continue
        fi

        # now write the query to the file
        echo "${line}" >> "${_query_file}"

        codeql_shell_regex_select="^select "

        if [[ "${line}" =~ $codeql_shell_regex_select ]]; then
            if ! codeql query run \
            --database="${_db_path}" \
            --output="${_bqrs_path}" \
            --quiet \
            --threads="${_codeql_cores}" \
            --ram="${_codeql_ram}" \
            -- "${_query_file}"; then
                codeql_shell_restart
                continue
            fi

            if [[ "on" == "${_codeql_shell_paged}" ]]; then
                if ! codeql bqrs decode \
                --format=${_out_format} \
                -J="-Xmx${_codeql_ram}m" \
                -- "${_bqrs_path}" | less; then
                    codeql_shell_restart
                    continue
                fi
            else
                if ! codeql bqrs decode \
                --format=${_out_format} \
                -J="-Xmx${_codeql_ram}m" \
                -- "${_bqrs_path}"; then
                    codeql_shell_restart
                    continue
                fi
            fi

            codeql_shell_restart
            continue
        else
            codeql_shell_cont
            continue
        fi
    done
}

function main {
    if [[ $# -ne 1 ]]; then
        codeql_shell_help
        exit 1
    fi

    if [[ $1 == "--help" || $1 == "-h" ]]; then
        codeql_shell_help
        exit 0
    fi

    if ! command -v codeql &> /dev/null; then
        echo "[-] codeql not found" >&2
        echo "[.] Cross platform, install with 'gh codeql' after installing the GitHub CLI and the CodeQL extension for that" >&2
        echo "[.] On macOS, install with 'brew install codeql'" >&2
        echo "[.] You can also get the CodeQL release binary at https://" >&2
        exit 1
    fi

    if ! command -v jq &> /dev/null; then
        echo "[-] jq not found" >&2
        echo "[.] On Ubuntu/Debian, install with 'sudo apt install jq'" >&2
        echo "[.] On Fedora/RHEL, install with 'sudo dnf install jq'" >&2
        echo "[.] On macOS, install with 'brew install jq'" >&2
        exit 1
    fi

    if [[ ! -d $1 && ! -f $1 ]]; then
        echo "[-] Database not found" >&2
        exit 1
    fi

    # if the database is a zip file, not a directory, extract it to a temporary folder
    if [[ -f $1 ]]; then
        _db_path=$(mktemp -d -t codeql-db)
        if ! codeql database unbundle "$1" -qqq --target="$_db_path"; then
            echo "[-] Error extracting database" >&2
            exit 1
        fi
    else
        _db_path=$1
    fi

    # find the language in the database
    _language=$(grep "primaryLanguage:" "$_db_path"/codeql-database.yml | cut -d" " -f2 | tr -d "'\"")

    _query_file_directory=$(mktemp -d -t codeql-query)
    _bqrs_path=$(mktemp -t bqrs.XXXXXXXXXX --tmpdir="${_query_file_directory}")
    _query_file=$(mktemp -t codeql-query --tmpdir="${_query_file_directory}").ql
    _out_format=text

    export -f codeql_shell_repl
    export -f codeql_shell_write_language
    export -f codeql_shell_restart
    export -f codeql_shell_restart_sigint
    export -f codeql_shell_cont
    export -f codeql_shell_prompt
    export -f codeql_shell_cleanup
    export -f codeql_shell_help
    export -f codeql_shell_help_lookup
    export -f codeql_shell_quit
    export -f codeql_shell_trunc

    export _db_path
    export _bqrs_path
    export _query_file
    export _out_format
    export _language
    export _query_file_directory
    export _code_shell_prompt
    export _codeql_cores='-1'   # by default, use all available cores except one
    export _codeql_ram
    export _codeql_shell_paged='off'  # by default, do not use less for output paging

    codeql_shell_set_ram
    codeql_shell_write_qlpack
    codeql_shell_resolve_languages

    if ! command -v rlwrap &> /dev/null; then
        echo "[.] For readline support, install rlwrap" >&2
        codeql_shell_repl
    else
        rlwrap bash -c "codeql_shell_repl"
    fi
}

main "$@"
